### PR TITLE
Add Submission Guide

### PR DESCRIPTION
**Pull request by DocOtak**

### CODE REVIEW

**Comment by DocOtak** [comment]
This is a draft until the full guide is present.

**Comment by DocOtak** [comment]
The draft version is intentional as it is worked on (wait for the rest of the content)

**Comment by DocOtak** [comment]
The CSV template is missing (or link to google sheet) but otherwise this is ready, we can do some followup PRs for the remaining fixes.

**Comment by DocOtak** [comment]
The file names determine the URL for the published, so those need to be checked with @kstocks before we go "live". (this can also be done in a followup PR)

**Review by asdossant — APPROVED** [review]

**Pull request merged**
